### PR TITLE
Added Vagrantfile, updated references to Google test frameworks

### PR DESCRIPTION
**Pull request by akappel**
I was following along with your tutorial and thought it might be helpful to add a Vagrantfile to get up and running quickly. It looks as though this project has gone stale though; do you have plans to restart development on it?

Also, although I was able to get the references sorted out for the Google test frameworks, I received an error while running `cmake --build build -- all test`:

image

### CODE REVIEW

**Comment by beardypig** [comment]
Cool, that's a good idea. It looks like gmock is not in the place it expects, perhaps the zip layout has changed or the cmake file needs to be updated. I will take a look at at it next week. 

I do plan to resume development on this project :-)

**Comment by akappel** [comment]
Awesome! Well I'm not too familiar with how `cmake` works to rectify that error. I'll have to get myself acclimated to the tool.

**Comment by beardypig** [comment]
There merged gtest and gmock in to one package, googletest... I need to refactor the cmake test stuff to fix it and I haven't found time yet :( Next week hopefully :)

**Comment by beardypig** [comment]
Thanks for adding the Vagrantfile, I've fixed the tests and merged the branch but I had to do it manually :)

**Comment by beardypig** [comment]
Ah one thing, [box-cutter/boxes/ubuntu1604-desktop](https://atlas.hashicorp.com/box-cutter/boxes/ubuntu1604-desktop) is not available for the virtualbox provider seems like they updated it but something was not set up correctly.

**Comment by akappel** [comment]
Awesome! I'll look into the virtualbox thing. Not sure why it would up and stop working.

**Pull request closed without merging**
